fs: f2fs: Remove cold parameter for 'pagevec_init'
Required after https://github.com/Stratosphere-Kernel/android_kernel_xiaomi_surya/commit/adf3e99e1eb2526878ac1286d4e1c493c333a6e5

Fixes compilation:
/fs/f2fs/compress.c:1820:22: error: too many arguments to function call, expected single argument 'pvec', have 2 arguments
        pagevec_init(&pvec, 0);
        ~~~~~~~~~~~~        ^
/home/taalojarvi/android_kernel_xiaomi_surya/include/linux/pagevec.h:53:20: note: 'pagevec_init' declared here
static inline void pagevec_init(struct pagevec *pvec)
                   ^
1 error generated.

Signed-off-by: taalojarvi <sreedevan05@gmail.com>