fs: erofs: add flags to xattr_generic_get
Required after c4443e209d937f1d402a3f878b81588eb4fcecf3
Referenced 3cc6f537baea0b1e261c14bef718a80696992dc3

Fixes:
error: incompatible function pointer types initializing 'int (*)(const struct xattr_handler *, struct dentry *, struct inode *, const char *, void *, size_t, int)' (aka 'int (*)(const struct xattr_handler *, struct dentry *, struct inode *, const char *, void *, unsigned long, int)') with an expression of type 'int (const struct xattr_handler *, struct dentry *, struct inode *, const char *, void *, size_t)' (aka 'int (const struct xattr_handler *, struct dentry *, struct inode *, const char *, void *, unsigned long)') [-Werror,-Wincompatible-function-pointer-types]
        .get    = erofs_xattr_generic_get,
                  ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: taalojarvi <sreedevan05@gmail.com>